# Generated by Django 2.2.2 on 2019-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
